/**
 * Apple Music / iTunes top-level genres (plus a few common electronic
 * sub-genres people actually tag with). Used to back the genre combobox — the
 * field still accepts free text, this just supplies the approved suggestions.
 */
export const ITUNES_GENRES: string[] = [
  'Alternative',
  'Ambient',
  'Blues',
  'Classical',
  'Country',
  'Dance',
  'Disco',
  'Drum & Bass',
  'Dubstep',
  'Easy Listening',
  'Electronic',
  'Folk',
  'Funk',
  'Gospel',
  'Hardstyle',
  'Hip-Hop/Rap',
  'Holiday',
  'House',
  'Indie',
  'Industrial',
  'Instrumental',
  'J-Pop',
  'Jazz',
  'K-Pop',
  'Latin',
  'Lo-Fi',
  'Metal',
  'New Age',
  'Opera',
  'Pop',
  'Punk',
  'R&B/Soul',
  'Reggae',
  'Reggaeton',
  'Rock',
  'Singer/Songwriter',
  'Ska',
  'Soul',
  'Soundtrack',
  'Spoken Word',
  'Synthwave',
  'Techno',
  'Trance',
  'Trap',
  'Vaporwave',
  'World'
]
